# Generated by Django 2.2.2 on 2019-06-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(choices=[('en_US', 'English'), ('pt_BR', 'Brazilian Portuguese')], max_length=5)),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('BRL', 'Brazilian Real')], max_length=3)),
                ('phone_number', models.CharField(max_length=40)),
            ],
        ),
    ]
