# Generated by Django 2.2.2 on 2019-06-24 22:33

import app.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(choices=[('en_US', 'English'), ('pt_BR', 'Brazilian Portuguese')], max_length=5, verbose_name='Language')),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('BRL', 'Real')], max_length=3, verbose_name='Currency')),
                ('phone_number', models.CharField(max_length=40, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=app.models.PointField(base_field=models.FloatField(), size=2), size=None)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='app.Provider')),
            ],
        ),
    ]
